const ActionTypes = {
  INITIALIZE_DATA: "INITIALIZE_DATA",
  FETCH_REPOS: "FETCH_REPOS",
  FETCHING_REPOS: "FETCHING_REPOS",
  FETCH_REPOS_SUCCESS: "FETCH_REPOS_SUCCESS",
  DONE_FETCHING_REPOS: "DONE_FETCHING_REPOS",
  FETCH_REPOS_FAILED: "FETCH_REPOS_FAILED"
}

module.exports = Object.freeze(ActionTypes);